# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=220)),
                ('body', models.CharField(max_length=520)),
            ],
        ),
    ]
